--[[
 .____                  ________ ___.    _____                           __                
 |    |    __ _______   \_____  \\_ |___/ ____\_ __  ______ ____ _____ _/  |_  ___________ 
 |    |   |  |  \__  \   /   |   \| __ \   __\  |  \/  ___// ___\\__  \\   __\/  _ \_  __ \
 |    |___|  |  // __ \_/    |    \ \_\ \  | |  |  /\___ \\  \___ / __ \|  | (  <_> )  | \/
 |_______ \____/(____  /\_______  /___  /__| |____//____  >\___  >____  /__|  \____/|__|   
         \/          \/         \/    \/                \/     \/     \/                   
          \_Welcome to LuaObfuscator.com   (Alpha 0.10.9) ~  Much Love, Ferib 

]]--

local v0=game.Players.LocalPlayer;local v1=game:GetService("UserInputService");local v2=game:GetService("RunService");local v3="https://raw.githubusercontent.com/Lenox31/Script---Tower-Of-Hell/main/";local function v4(v13) local v14,v15=pcall(function() return game:HttpGet(v3   .. v13   .. ".lua?t="   .. os.time() );end);if  not v14 then warn("Erreur de connexion : "   .. v13 );return nil;end local v16,v17=loadstring(v15);if  not v16 then warn("Erreur de syntaxe dans "   .. v13   .. " : "   .. tostring(v17) );return nil;end return v16();end local v5=v4("ThemeConfig");local v6=v4("Cheats");local v7=v4("UI");if  not v6 then warn("Cheats introuvable");return;end if  not v7 then warn("UI introuvable");return;end v6.isAutoPiloting=false;v6.flyKeybind=Enum.KeyCode.F;local v11=v7.Create(v5,v6);local function v12(v18) local v19=v18:WaitForChild("HumanoidRootPart",10);local v20=v18:WaitForChild("Humanoid",10);if ( not v19 or  not v20) then return;end if v6.flying then v6.enableFly(v19,v20);end if v6.godModeActive then v6.enableGodMode(v20);end end v0.CharacterAdded:Connect(v12);if v0.Character then v12(v0.Character);end v2.RenderStepped:Connect(function() if v6.updateDirections then v6.updateDirections(workspace.CurrentCamera,v1);end end);v11.autoBtn.MouseButton1Click:Connect(function() if v6.isAutoPiloting then return;end task.spawn(function() local v23=v0.Character;local v24=v23 and v23:FindFirstChild("HumanoidRootPart") ;local v25=v23 and v23:FindFirstChild("Humanoid") ;if (v24 and v25) then local v29,v30=pcall(function() v6.runWaypoints(v24,v25);end);if  not v29 then warn("Erreur Auto-Tower : "   .. tostring(v30) );end v6.isAutoPiloting=false;end end);end);v1.InputBegan:Connect(function(v21,v22) if v22 then return;end if (v6.flyKeybind and (v21.KeyCode==v6.flyKeybind)) then local v26=v0.Character;local v27=v26 and v26:FindFirstChild("HumanoidRootPart") ;local v28=v26 and v26:FindFirstChild("Humanoid") ;if (v27 and v28) then if v6.flying then v6.disableFly(v28);if v11.flySwitch then v11.flySwitch.BackgroundColor3=v5.THEME.AccentGray;v11.flyCircle:TweenPosition(UDim2.new(0,3,0.5,0),"Out","Quad",0.2,true);end else v6.enableFly(v27,v28);if v11.flySwitch then v11.flySwitch.BackgroundColor3=v5.THEME.AccentBlue;v11.flyCircle:TweenPosition(UDim2.new(1, -19,0.5,0),"Out","Quad",0.2,true);end end end end end);